//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISOS.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageHelper {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageHelper() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RISOS.Localization.LanguageHelper", typeof(LanguageHelper).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        internal static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Details.
        /// </summary>
        internal static string AcademicDetails {
            get {
                return ResourceManager.GetString("AcademicDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom subject.
        /// </summary>
        internal static string AddCustomSubject {
            get {
                return ResourceManager.GetString("AddCustomSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add recognized year.
        /// </summary>
        internal static string AddRecognizedYear {
            get {
                return ResourceManager.GetString("AddRecognizedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust study duration.
        /// </summary>
        internal static string AdjustYears {
            get {
                return ResourceManager.GetString("AdjustYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        internal static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear local data.
        /// </summary>
        internal static string ClearStorage {
            get {
                return ResourceManager.GetString("ClearStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create clone.
        /// </summary>
        internal static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Type.
        /// </summary>
        internal static string CompletionType {
            get {
                return ResourceManager.GetString("CompletionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colloquium.
        /// </summary>
        internal static string CompletionTypeCol {
            get {
                return ResourceManager.GetString("CompletionTypeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course-unit credit.
        /// </summary>
        internal static string CompletionTypeCr {
            get {
                return ResourceManager.GetString("CompletionTypeCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course-unit credit and examination.
        /// </summary>
        internal static string CompletionTypeCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course-unit credit and final semester project.
        /// </summary>
        internal static string CompletionTypeCrFsp {
            get {
                return ResourceManager.GetString("CompletionTypeCrFsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination.
        /// </summary>
        internal static string CompletionTypeDrEx {
            get {
                return ResourceManager.GetString("CompletionTypeDrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination.
        /// </summary>
        internal static string CompletionTypeEx {
            get {
                return ResourceManager.GetString("CompletionTypeEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Except DD.
        /// </summary>
        internal static string CompletionTypeExDd {
            get {
                return ResourceManager.GetString("CompletionTypeExDd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graded course-unit credit.
        /// </summary>
        internal static string CompletionTypeGCr {
            get {
                return ResourceManager.GetString("CompletionTypeGCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation of doctoral study.
        /// </summary>
        internal static string CompletionTypeHds {
            get {
                return ResourceManager.GetString("CompletionTypeHds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation of study.
        /// </summary>
        internal static string CompletionTypeHs {
            get {
                return ResourceManager.GetString("CompletionTypeHs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final semester project.
        /// </summary>
        internal static string CompletionTypeKp {
            get {
                return ResourceManager.GetString("CompletionTypeKp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No final classification.
        /// </summary>
        internal static string CompletionTypeNone {
            get {
                return ResourceManager.GetString("CompletionTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized colloquium.
        /// </summary>
        internal static string CompletionTypeRCol {
            get {
                return ResourceManager.GetString("CompletionTypeRCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized course-unit credit.
        /// </summary>
        internal static string CompletionTypeRCr {
            get {
                return ResourceManager.GetString("CompletionTypeRCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized course-unit credit and examination.
        /// </summary>
        internal static string CompletionTypeRCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeRCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized.
        /// </summary>
        internal static string CompletionTypeRec {
            get {
                return ResourceManager.GetString("CompletionTypeRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized examination.
        /// </summary>
        internal static string CompletionTypeRecCr {
            get {
                return ResourceManager.GetString("CompletionTypeRecCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized examination.
        /// </summary>
        internal static string CompletionTypeREx {
            get {
                return ResourceManager.GetString("CompletionTypeREx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized graded course-unit credit.
        /// </summary>
        internal static string CompletionTypeRgCr {
            get {
                return ResourceManager.GetString("CompletionTypeRgCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized year of study.
        /// </summary>
        internal static string CompletionTypeRVol {
            get {
                return ResourceManager.GetString("CompletionTypeRVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col.
        /// </summary>
        internal static string CompletionTypeShortCol {
            get {
                return ResourceManager.GetString("CompletionTypeShortCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cr.
        /// </summary>
        internal static string CompletionTypeShortCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cr,Ex.
        /// </summary>
        internal static string CompletionTypeShortCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cr,Fsp.
        /// </summary>
        internal static string CompletionTypeShortCrFsp {
            get {
                return ResourceManager.GetString("CompletionTypeShortCrFsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr,Ex.
        /// </summary>
        internal static string CompletionTypeShortDrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortDrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex.
        /// </summary>
        internal static string CompletionTypeShortEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex,DD.
        /// </summary>
        internal static string CompletionTypeShortExDd {
            get {
                return ResourceManager.GetString("CompletionTypeShortExDd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCr.
        /// </summary>
        internal static string CompletionTypeShortGCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortGCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hds.
        /// </summary>
        internal static string CompletionTypeShortHds {
            get {
                return ResourceManager.GetString("CompletionTypeShortHds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hs.
        /// </summary>
        internal static string CompletionTypeShortHs {
            get {
                return ResourceManager.GetString("CompletionTypeShortHs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kp.
        /// </summary>
        internal static string CompletionTypeShortKp {
            get {
                return ResourceManager.GetString("CompletionTypeShortKp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CompletionTypeShortNone {
            get {
                return ResourceManager.GetString("CompletionTypeShortNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCol.
        /// </summary>
        internal static string CompletionTypeShortRCol {
            get {
                return ResourceManager.GetString("CompletionTypeShortRCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCr.
        /// </summary>
        internal static string CompletionTypeShortRCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortRCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCr,Ex.
        /// </summary>
        internal static string CompletionTypeShortRCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortRCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec.
        /// </summary>
        internal static string CompletionTypeShortRec {
            get {
                return ResourceManager.GetString("CompletionTypeShortRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecCr.
        /// </summary>
        internal static string CompletionTypeShortRecCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortRecCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REx.
        /// </summary>
        internal static string CompletionTypeShortREx {
            get {
                return ResourceManager.GetString("CompletionTypeShortREx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rg,Cr.
        /// </summary>
        internal static string CompletionTypeShortRgCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortRgCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVol.
        /// </summary>
        internal static string CompletionTypeShortRVol {
            get {
                return ResourceManager.GetString("CompletionTypeShortRVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sp,Cr,Ex.
        /// </summary>
        internal static string CompletionTypeShortSpCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortSpCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sp,Ex.
        /// </summary>
        internal static string CompletionTypeShortSpEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortSpEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SZZ.
        /// </summary>
        internal static string CompletionTypeShortSzz {
            get {
                return ResourceManager.GetString("CompletionTypeShortSzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CompletionTypeShortUnknown {
            get {
                return ResourceManager.GetString("CompletionTypeShortUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up,Za.
        /// </summary>
        internal static string CompletionTypeShortUpZa {
            get {
                return ResourceManager.GetString("CompletionTypeShortUpZa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization credit and examination.
        /// </summary>
        internal static string CompletionTypeSpCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeSpCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization examination.
        /// </summary>
        internal static string CompletionTypeSpEx {
            get {
                return ResourceManager.GetString("CompletionTypeSpEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final state examination.
        /// </summary>
        internal static string CompletionTypeSzz {
            get {
                return ResourceManager.GetString("CompletionTypeSzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CompletionTypeUnknown {
            get {
                return ResourceManager.GetString("CompletionTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized course-unit credit only.
        /// </summary>
        internal static string CompletionTypeUpZa {
            get {
                return ResourceManager.GetString("CompletionTypeUpZa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compulsory.
        /// </summary>
        internal static string Compulsory {
            get {
                return ResourceManager.GetString("Compulsory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compulsory elective.
        /// </summary>
        internal static string CompulsoryElective {
            get {
                return ResourceManager.GetString("CompulsoryElective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select subject from every group.
        /// </summary>
        internal static string CompulsoryElectiveErrorMessage {
            get {
                return ResourceManager.GetString("CompulsoryElectiveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compulsory-Elective.
        /// </summary>
        internal static string CompulsoryElectiveSingle {
            get {
                return ResourceManager.GetString("CompulsoryElectiveSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compulsory.
        /// </summary>
        internal static string CompulsorySingle {
            get {
                return ResourceManager.GetString("CompulsorySingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cr.
        /// </summary>
        internal static string Cr {
            get {
                return ResourceManager.GetString("Cr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits_y {
            get {
                return ResourceManager.GetString("Credits_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop your plan here or click. .
        /// </summary>
        internal static string DropJSON {
            get {
                return ResourceManager.GetString("DropJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elective.
        /// </summary>
        internal static string Elective {
            get {
                return ResourceManager.GetString("Elective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elective.
        /// </summary>
        internal static string ElectiveSingle {
            get {
                return ResourceManager.GetString("ElectiveSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is corrupted or has an invalid structure..
        /// </summary>
        internal static string FileInvalid {
            get {
                return ResourceManager.GetString("FileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been successfully uploaded and verified..
        /// </summary>
        internal static string FileVerified {
            get {
                return ResourceManager.GetString("FileVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Mathematical Analysis.
        /// </summary>
        internal static string IMA {
            get {
                return ResourceManager.GetString("IMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. IMA1, IMA2.
        /// </summary>
        internal static string IMAAbbreviation {
            get {
                return ResourceManager.GetString("IMAAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compulsory-Elective.
        /// </summary>
        internal static string Import_JSOn {
            get {
                return ResourceManager.GetString("Import JSOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import your plan.
        /// </summary>
        internal static string ImportJSON {
            get {
                return ResourceManager.GetString("ImportJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format. Please select a .json file..
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required.
        /// </summary>
        internal static string IsRequired_a {
            get {
                return ResourceManager.GetString("IsRequired_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required.
        /// </summary>
        internal static string IsRequired_y {
            get {
                return ResourceManager.GetString("IsRequired_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        internal static string Language_Czech {
            get {
                return ResourceManager.GetString("Language_Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change forces refresh of the app after saving.
        /// </summary>
        internal static string LanguageAlert {
            get {
                return ResourceManager.GetString("LanguageAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string LanguageToggleTooltip {
            get {
                return ResourceManager.GetString("LanguageToggleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last data update.
        /// </summary>
        internal static string LastDataUpdate {
            get {
                return ResourceManager.GetString("LastDataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Link.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum semester.
        /// </summary>
        internal static string MinimumSemester {
            get {
                return ResourceManager.GetString("MinimumSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest allowed semester.
        /// </summary>
        internal static string MinSemesterHelperText {
            get {
                return ResourceManager.GetString("MinSemesterHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * You must select a file (.json) before importing..
        /// </summary>
        internal static string MissingFile {
            get {
                return ResourceManager.GetString("MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        internal static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove recognized year.
        /// </summary>
        internal static string RemoveRecognizedYear {
            get {
                return ResourceManager.GetString("RemoveRecognizedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify required credits, go to settings to adjust.
        /// </summary>
        internal static string RequiredWarning {
            get {
                return ResourceManager.GetString("RequiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake.
        /// </summary>
        internal static string Retake {
            get {
                return ResourceManager.GetString("Retake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add retaken subject.
        /// </summary>
        internal static string RetakeSnackbarFailure {
            get {
                return ResourceManager.GetString("RetakeSnackbarFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retaken subject added to.
        /// </summary>
        internal static string RetakeSnackbarText {
            get {
                return ResourceManager.GetString("RetakeSnackbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        internal static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semester.
        /// </summary>
        internal static string Semester_u {
            get {
                return ResourceManager.GetString("Semester_u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester Season.
        /// </summary>
        internal static string SemesterSeason {
            get {
                return ResourceManager.GetString("SemesterSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Settings.
        /// </summary>
        internal static string SettingsDialog_AcademicSettings {
            get {
                return ResourceManager.GetString("SettingsDialog_AcademicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        internal static string SettingsDialog_DarkMode {
            get {
                return ResourceManager.GetString("SettingsDialog_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsDialog_Language {
            get {
                return ResourceManager.GetString("SettingsDialog_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override required credits.
        /// </summary>
        internal static string SettingsDialog_OverrideCredits {
            get {
                return ResourceManager.GetString("SettingsDialog_OverrideCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color palette.
        /// </summary>
        internal static string SettingsDialog_Palette {
            get {
                return ResourceManager.GetString("SettingsDialog_Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Credits.
        /// </summary>
        internal static string SettingsDialog_RequiredCredits {
            get {
                return ResourceManager.GetString("SettingsDialog_RequiredCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsDialog_Save {
            get {
                return ResourceManager.GetString("SettingsDialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsDialog_Title {
            get {
                return ResourceManager.GetString("SettingsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy link. Try doing it manually.
        /// </summary>
        internal static string ShareFailure {
            get {
                return ResourceManager.GetString("ShareFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share link added to clipboard.
        /// </summary>
        internal static string ShareSuccess {
            get {
                return ResourceManager.GetString("ShareSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Share link will override local appstate after openning.
        /// </summary>
        internal static string ShareWarning {
            get {
                return ResourceManager.GetString("ShareWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show course info.
        /// </summary>
        internal static string ShowCourseInfo {
            get {
                return ResourceManager.GetString("ShowCourseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show study program info.
        /// </summary>
        internal static string ShowProgramInfo {
            get {
                return ResourceManager.GetString("ShowProgramInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study program.
        /// </summary>
        internal static string StudyProgram {
            get {
                return ResourceManager.GetString("StudyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study progress.
        /// </summary>
        internal static string StudyProgress {
            get {
                return ResourceManager.GetString("StudyProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject added.
        /// </summary>
        internal static string SubjectAdded {
            get {
                return ResourceManager.GetString("SubjectAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject type.
        /// </summary>
        internal static string SubjectType {
            get {
                return ResourceManager.GetString("SubjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        internal static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorblind.
        /// </summary>
        internal static string Theme_Colorblind {
            get {
                return ResourceManager.GetString("Theme_Colorblind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Theme_Default {
            get {
                return ResourceManager.GetString("Theme_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red-Green (Common).
        /// </summary>
        internal static string Theme_Deuteranopia {
            get {
                return ResourceManager.GetString("Theme_Deuteranopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        internal static string Theme_HighContrast {
            get {
                return ResourceManager.GetString("Theme_HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red-Green (Protan).
        /// </summary>
        internal static string Theme_Protanopia {
            get {
                return ResourceManager.GetString("Theme_Protanopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue-Yellow.
        /// </summary>
        internal static string Theme_Tritanopia {
            get {
                return ResourceManager.GetString("Theme_Tritanopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        internal static string Unassigned {
            get {
                return ResourceManager.GetString("Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned Subjects.
        /// </summary>
        internal static string UnassignedSubjects {
            get {
                return ResourceManager.GetString("UnassignedSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a JSON file to restore your data. .
        /// </summary>
        internal static string UploadData {
            get {
                return ResourceManager.GetString("UploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        internal static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string Years_Few {
            get {
                return ResourceManager.GetString("Years_Few", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string Years_Many {
            get {
                return ResourceManager.GetString("Years_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Years_One {
            get {
                return ResourceManager.GetString("Years_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year total.
        /// </summary>
        internal static string YearTotal {
            get {
                return ResourceManager.GetString("YearTotal", resourceCulture);
            }
        }
    }
}
