//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISOS.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageHelper {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageHelper() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RISOS.Localization.LanguageHelper", typeof(LanguageHelper).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Compulsory {
            get {
                return ResourceManager.GetString("Compulsory", resourceCulture);
            }
        }
        
        internal static string LanguageToggleTooltip {
            get {
                return ResourceManager.GetString("LanguageToggleTooltip", resourceCulture);
            }
        }
        
        internal static string Import_JSOn {
            get {
                return ResourceManager.GetString("Import JSOn", resourceCulture);
            }
        }
        
        internal static string Elective {
            get {
                return ResourceManager.GetString("Elective", resourceCulture);
            }
        }
        
        internal static string StudyProgram {
            get {
                return ResourceManager.GetString("StudyProgram", resourceCulture);
            }
        }
        
        internal static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        internal static string ExportAsImage {
            get {
                return ResourceManager.GetString("ExportAsImage", resourceCulture);
            }
        }
        
        internal static string ExportAsJson {
            get {
                return ResourceManager.GetString("ExportAsJson", resourceCulture);
            }
        }
        
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string SearchSubjectsTooltip {
            get {
                return ResourceManager.GetString("SearchSubjectsTooltip", resourceCulture);
            }
        }
        
        internal static string RemoveRecognizedYear {
            get {
                return ResourceManager.GetString("RemoveRecognizedYear", resourceCulture);
            }
        }
        
        internal static string AddRecognizedYear {
            get {
                return ResourceManager.GetString("AddRecognizedYear", resourceCulture);
            }
        }
        
        internal static string StudyProgress {
            get {
                return ResourceManager.GetString("StudyProgress", resourceCulture);
            }
        }
        
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        internal static string Sorted {
            get {
                return ResourceManager.GetString("Sorted", resourceCulture);
            }
        }
        
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        internal static string CreditsWarning {
            get {
                return ResourceManager.GetString("CreditsWarning", resourceCulture);
            }
        }
        
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        internal static string Years_One {
            get {
                return ResourceManager.GetString("Years_One", resourceCulture);
            }
        }
        
        internal static string Years_Few {
            get {
                return ResourceManager.GetString("Years_Few", resourceCulture);
            }
        }
        
        internal static string Years_Many {
            get {
                return ResourceManager.GetString("Years_Many", resourceCulture);
            }
        }
        
        internal static string AdjustYears {
            get {
                return ResourceManager.GetString("AdjustYears", resourceCulture);
            }
        }
        
        internal static string SearchAllSubjects {
            get {
                return ResourceManager.GetString("SearchAllSubjects", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string AddCustomSubject {
            get {
                return ResourceManager.GetString("AddCustomSubject", resourceCulture);
            }
        }
        
        internal static string CompulsorySingle {
            get {
                return ResourceManager.GetString("CompulsorySingle", resourceCulture);
            }
        }
        
        internal static string CompulsoryElectiveSingle {
            get {
                return ResourceManager.GetString("CompulsoryElectiveSingle", resourceCulture);
            }
        }
        
        internal static string ElectiveSingle {
            get {
                return ResourceManager.GetString("ElectiveSingle", resourceCulture);
            }
        }
        
        internal static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
        
        internal static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        internal static string Cr {
            get {
                return ResourceManager.GetString("Cr", resourceCulture);
            }
        }
        
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        internal static string CompletionTypeNone {
            get {
                return ResourceManager.GetString("CompletionTypeNone", resourceCulture);
            }
        }
        
        internal static string CompletionTypeCr {
            get {
                return ResourceManager.GetString("CompletionTypeCr", resourceCulture);
            }
        }
        
        internal static string CompletionTypeGCr {
            get {
                return ResourceManager.GetString("CompletionTypeGCr", resourceCulture);
            }
        }
        
        internal static string CompletionTypeCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeCrEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeEx {
            get {
                return ResourceManager.GetString("CompletionTypeEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeCol {
            get {
                return ResourceManager.GetString("CompletionTypeCol", resourceCulture);
            }
        }
        
        internal static string CompletionTypeKp {
            get {
                return ResourceManager.GetString("CompletionTypeKp", resourceCulture);
            }
        }
        
        internal static string CompletionTypeRec {
            get {
                return ResourceManager.GetString("CompletionTypeRec", resourceCulture);
            }
        }
        
        internal static string CompletionTypeSzz {
            get {
                return ResourceManager.GetString("CompletionTypeSzz", resourceCulture);
            }
        }
        
        internal static string CompletionTypeRCr {
            get {
                return ResourceManager.GetString("CompletionTypeRCr", resourceCulture);
            }
        }
        
        internal static string CompletionTypeRgCr {
            get {
                return ResourceManager.GetString("CompletionTypeRgCr", resourceCulture);
            }
        }
        
        internal static string CompletionTypeRCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeRCrEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeREx {
            get {
                return ResourceManager.GetString("CompletionTypeREx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeHs {
            get {
                return ResourceManager.GetString("CompletionTypeHs", resourceCulture);
            }
        }
        
        internal static string CompletionTypeHds {
            get {
                return ResourceManager.GetString("CompletionTypeHds", resourceCulture);
            }
        }
        
        internal static string CompletionTypeUpZa {
            get {
                return ResourceManager.GetString("CompletionTypeUpZa", resourceCulture);
            }
        }
        
        internal static string CompletionTypeRVol {
            get {
                return ResourceManager.GetString("CompletionTypeRVol", resourceCulture);
            }
        }
        
        internal static string CompletionTypeCrFsp {
            get {
                return ResourceManager.GetString("CompletionTypeCrFsp", resourceCulture);
            }
        }
        
        internal static string CompletionTypeDrEx {
            get {
                return ResourceManager.GetString("CompletionTypeDrEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeRecCr {
            get {
                return ResourceManager.GetString("CompletionTypeRecCr", resourceCulture);
            }
        }
        
        internal static string CompletionTypeExDd {
            get {
                return ResourceManager.GetString("CompletionTypeExDd", resourceCulture);
            }
        }
        
        internal static string CompletionTypeSpEx {
            get {
                return ResourceManager.GetString("CompletionTypeSpEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeSpCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeSpCrEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeRCol {
            get {
                return ResourceManager.GetString("CompletionTypeRCol", resourceCulture);
            }
        }
        
        internal static string CompletionTypeUnknown {
            get {
                return ResourceManager.GetString("CompletionTypeUnknown", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        internal static string Unassigned {
            get {
                return ResourceManager.GetString("Unassigned", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortCol {
            get {
                return ResourceManager.GetString("CompletionTypeShortCol", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortCr", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortCrEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortCrFsp {
            get {
                return ResourceManager.GetString("CompletionTypeShortCrFsp", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortDrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortDrEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortExDd {
            get {
                return ResourceManager.GetString("CompletionTypeShortExDd", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortGCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortGCr", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortHds {
            get {
                return ResourceManager.GetString("CompletionTypeShortHds", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortHs {
            get {
                return ResourceManager.GetString("CompletionTypeShortHs", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortKp {
            get {
                return ResourceManager.GetString("CompletionTypeShortKp", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortNone {
            get {
                return ResourceManager.GetString("CompletionTypeShortNone", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortRCol {
            get {
                return ResourceManager.GetString("CompletionTypeShortRCol", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortRCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortRCr", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortRCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortRCrEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortRec {
            get {
                return ResourceManager.GetString("CompletionTypeShortRec", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortRecCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortRecCr", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortREx {
            get {
                return ResourceManager.GetString("CompletionTypeShortREx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortRgCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortRgCr", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortRVol {
            get {
                return ResourceManager.GetString("CompletionTypeShortRVol", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortSpCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortSpCrEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortSpEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortSpEx", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortSzz {
            get {
                return ResourceManager.GetString("CompletionTypeShortSzz", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortUnknown {
            get {
                return ResourceManager.GetString("CompletionTypeShortUnknown", resourceCulture);
            }
        }
        
        internal static string CompletionTypeShortUpZa {
            get {
                return ResourceManager.GetString("CompletionTypeShortUpZa", resourceCulture);
            }
        }
        
        internal static string SemesterTotal {
            get {
                return ResourceManager.GetString("SemesterTotal", resourceCulture);
            }
        }
        
        internal static string YearTotal {
            get {
                return ResourceManager.GetString("YearTotal", resourceCulture);
            }
        }
        
        internal static string UnassignedSubjects {
            get {
                return ResourceManager.GetString("UnassignedSubjects", resourceCulture);
            }
        }
        
        internal static string ShowCourseInfo {
            get {
                return ResourceManager.GetString("ShowCourseInfo", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string IsRequired_y {
            get {
                return ResourceManager.GetString("IsRequired_y", resourceCulture);
            }
        }
        
        internal static string IsRequired_a {
            get {
                return ResourceManager.GetString("IsRequired_a", resourceCulture);
            }
        }
        
        internal static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        internal static string AcademicDetails {
            get {
                return ResourceManager.GetString("AcademicDetails", resourceCulture);
            }
        }
        
        internal static string Credits_y {
            get {
                return ResourceManager.GetString("Credits_y", resourceCulture);
            }
        }
        
        internal static string SubjectType {
            get {
                return ResourceManager.GetString("SubjectType", resourceCulture);
            }
        }
        
        internal static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        internal static string SemesterSeason {
            get {
                return ResourceManager.GetString("SemesterSeason", resourceCulture);
            }
        }
        
        internal static string CompletionType {
            get {
                return ResourceManager.GetString("CompletionType", resourceCulture);
            }
        }
        
        internal static string MinimumSemester {
            get {
                return ResourceManager.GetString("MinimumSemester", resourceCulture);
            }
        }
        
        internal static string IMA {
            get {
                return ResourceManager.GetString("IMA", resourceCulture);
            }
        }
        
        internal static string MinSemesterHelperText {
            get {
                return ResourceManager.GetString("MinSemesterHelperText", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        internal static string IMAAbbreviation {
            get {
                return ResourceManager.GetString("IMAAbbreviation", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string SettingsDialog_Title {
            get {
                return ResourceManager.GetString("SettingsDialog_Title", resourceCulture);
            }
        }
        
        internal static string SettingsDialog_Save {
            get {
                return ResourceManager.GetString("SettingsDialog_Save", resourceCulture);
            }
        }
        
        internal static string SettingsDialog_Language {
            get {
                return ResourceManager.GetString("SettingsDialog_Language", resourceCulture);
            }
        }
        
        internal static string SettingsDialog_AcademicSettings {
            get {
                return ResourceManager.GetString("SettingsDialog_AcademicSettings", resourceCulture);
            }
        }
        
        internal static string SettingsDialog_OverrideCredits {
            get {
                return ResourceManager.GetString("SettingsDialog_OverrideCredits", resourceCulture);
            }
        }
        
        internal static string SettingsDialog_RequiredCredits {
            get {
                return ResourceManager.GetString("SettingsDialog_RequiredCredits", resourceCulture);
            }
        }
        
        internal static string Language_Czech {
            get {
                return ResourceManager.GetString("Language_Czech", resourceCulture);
            }
        }
        
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        internal static string LanguageAlert {
            get {
                return ResourceManager.GetString("LanguageAlert", resourceCulture);
            }
        }
        
        internal static string CompulsoryElectiveErrorMessage {
            get {
                return ResourceManager.GetString("CompulsoryElectiveErrorMessage", resourceCulture);
            }
        }
        
        internal static string ImportJSON {
            get {
                return ResourceManager.GetString("ImportJSON", resourceCulture);
            }
        }
        
        internal static string UploadData {
            get {
                return ResourceManager.GetString("UploadData", resourceCulture);
            }
        }
        
        internal static string DropJSON {
            get {
                return ResourceManager.GetString("DropJSON", resourceCulture);
            }
        }
        
        internal static string CompulsoryElective {
            get {
                return ResourceManager.GetString("CompulsoryElective", resourceCulture);
            }
        }
        
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        internal static string FileVerified {
            get {
                return ResourceManager.GetString("FileVerified", resourceCulture);
            }
        }
        
        internal static string FileInvalid {
            get {
                return ResourceManager.GetString("FileInvalid", resourceCulture);
            }
        }
        
        internal static string MissingFile {
            get {
                return ResourceManager.GetString("MissingFile", resourceCulture);
            }
        }
        
        internal static string ShowProgramInfo {
            get {
                return ResourceManager.GetString("ShowProgramInfo", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string LastDataUpdate {
            get {
                return ResourceManager.GetString("LastDataUpdate", resourceCulture);
            }
        }
        
        internal static string Retake {
            get {
                return ResourceManager.GetString("Retake", resourceCulture);
            }
        }
        
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        internal static string SubjectAdded {
            get {
                return ResourceManager.GetString("SubjectAdded", resourceCulture);
            }
        }
        
        internal static string SubjectAlreadyInPlan {
            get {
                return ResourceManager.GetString("SubjectAlreadyInPlan", resourceCulture);
            }
        }
        
        internal static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        internal static string RetakeSnackbarText {
            get {
                return ResourceManager.GetString("RetakeSnackbarText", resourceCulture);
            }
        }
        
        internal static string Semester_u {
            get {
                return ResourceManager.GetString("Semester_u", resourceCulture);
            }
        }
        
        internal static string RetakeSnackbarFailure {
            get {
                return ResourceManager.GetString("RetakeSnackbarFailure", resourceCulture);
            }
        }
        
        internal static string ClearStorage {
            get {
                return ResourceManager.GetString("ClearStorage", resourceCulture);
            }
        }
        
        internal static string ShareSuccess {
            get {
                return ResourceManager.GetString("ShareSuccess", resourceCulture);
            }
        }
        
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string ShareWarning {
            get {
                return ResourceManager.GetString("ShareWarning", resourceCulture);
            }
        }
        
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        internal static string ShareFailure {
            get {
                return ResourceManager.GetString("ShareFailure", resourceCulture);
            }
        }
        
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        internal static string SettingsDialog_DarkMode {
            get {
                return ResourceManager.GetString("SettingsDialog_DarkMode", resourceCulture);
            }
        }
        
        internal static string SettingsDialog_Palette {
            get {
                return ResourceManager.GetString("SettingsDialog_Palette", resourceCulture);
            }
        }
        
        internal static string Theme_Default {
            get {
                return ResourceManager.GetString("Theme_Default", resourceCulture);
            }
        }
        
        internal static string Theme_Colorblind {
            get {
                return ResourceManager.GetString("Theme_Colorblind", resourceCulture);
            }
        }
        
        internal static string Theme_Deuteranopia {
            get {
                return ResourceManager.GetString("Theme_Deuteranopia", resourceCulture);
            }
        }
        
        internal static string Theme_Protanopia {
            get {
                return ResourceManager.GetString("Theme_Protanopia", resourceCulture);
            }
        }
        
        internal static string Theme_Tritanopia {
            get {
                return ResourceManager.GetString("Theme_Tritanopia", resourceCulture);
            }
        }
        
        internal static string Theme_HighContrast {
            get {
                return ResourceManager.GetString("Theme_HighContrast", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        internal static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        internal static string ReportBug {
            get {
                return ResourceManager.GetString("ReportBug", resourceCulture);
            }
        }
        
        internal static string RequestFeature {
            get {
                return ResourceManager.GetString("RequestFeature", resourceCulture);
            }
        }
        
        internal static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        internal static string SportsCreditsLimitWarning {
            get {
                return ResourceManager.GetString("SportsCreditsLimitWarning", resourceCulture);
            }
        }
        
        internal static string DuplicateSportsWarning {
            get {
                return ResourceManager.GetString("DuplicateSportsWarning", resourceCulture);
            }
        }
        
        internal static string ShareHelperText {
            get {
                return ResourceManager.GetString("ShareHelperText", resourceCulture);
            }
        }
        
        internal static string SubjectUpdated {
            get {
                return ResourceManager.GetString("SubjectUpdated", resourceCulture);
            }
        }
        
        internal static string DataFailed {
            get {
                return ResourceManager.GetString("DataFailed", resourceCulture);
            }
        }
        
        internal static string ConfirmDecrese {
            get {
                return ResourceManager.GetString("ConfirmDecrese", resourceCulture);
            }
        }
        
        internal static string ConfirmDecreseMessage {
            get {
                return ResourceManager.GetString("ConfirmDecreseMessage", resourceCulture);
            }
        }
        
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        internal static string CompulsorySubjectDeleteError {
            get {
                return ResourceManager.GetString("CompulsorySubjectDeleteError", resourceCulture);
            }
        }
        
        internal static string CompleteAllSubjectsInSemester {
            get {
                return ResourceManager.GetString("CompleteAllSubjectsInSemester", resourceCulture);
            }
        }
        
        internal static string SortSemesterSubjects {
            get {
                return ResourceManager.GetString("SortSemesterSubjects", resourceCulture);
            }
        }
        
        internal static string RecognizedYearTitle {
            get {
                return ResourceManager.GetString("RecognizedYearTitle", resourceCulture);
            }
        }
        
        internal static string RecognizedSemester {
            get {
                return ResourceManager.GetString("RecognizedSemester", resourceCulture);
            }
        }
        
        internal static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        internal static string LatestUpdates {
            get {
                return ResourceManager.GetString("LatestUpdates", resourceCulture);
            }
        }
        
        internal static string WhatsNew_GlobalSearch {
            get {
                return ResourceManager.GetString("WhatsNew_GlobalSearch", resourceCulture);
            }
        }
        
        internal static string WhatsNew_SemesterQuickActions {
            get {
                return ResourceManager.GetString("WhatsNew_SemesterQuickActions", resourceCulture);
            }
        }
        
        internal static string WhatsNew_SportsTracking {
            get {
                return ResourceManager.GetString("WhatsNew_SportsTracking", resourceCulture);
            }
        }
        
        internal static string WhatsNew_TrashDropzone {
            get {
                return ResourceManager.GetString("WhatsNew_TrashDropzone", resourceCulture);
            }
        }
        
        internal static string WhatsNew_MobileOptimized {
            get {
                return ResourceManager.GetString("WhatsNew_MobileOptimized", resourceCulture);
            }
        }
        
        internal static string WhatsNew_Export {
            get {
                return ResourceManager.GetString("WhatsNew_Export", resourceCulture);
            }
        }
        
        internal static string WhatsNew_ThemeCustomization {
            get {
                return ResourceManager.GetString("WhatsNew_ThemeCustomization", resourceCulture);
            }
        }
        
        internal static string WhatsNew_PlanSharing {
            get {
                return ResourceManager.GetString("WhatsNew_PlanSharing", resourceCulture);
            }
        }
        
        internal static string WhatsNew_FullLanguageSupport {
            get {
                return ResourceManager.GetString("WhatsNew_FullLanguageSupport", resourceCulture);
            }
        }
        
        internal static string WhatsNew_CustomSubjectCreation {
            get {
                return ResourceManager.GetString("WhatsNew_CustomSubjectCreation", resourceCulture);
            }
        }
        
        internal static string WhatsNew_GpaPredictor {
            get {
                return ResourceManager.GetString("WhatsNew_GpaPredictor", resourceCulture);
            }
        }
        
        internal static string SelectProgramFirst {
            get {
                return ResourceManager.GetString("SelectProgramFirst", resourceCulture);
            }
        }
        
        internal static string SettingsDialog_GpaPredictor {
            get {
                return ResourceManager.GetString("SettingsDialog_GpaPredictor", resourceCulture);
            }
        }
        
        internal static string GradeSelection_Title {
            get {
                return ResourceManager.GetString("GradeSelection_Title", resourceCulture);
            }
        }
        
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        internal static string GpaStatistics {
            get {
                return ResourceManager.GetString("GpaStatistics", resourceCulture);
            }
        }
        
        internal static string GpaYearlyWeighted {
            get {
                return ResourceManager.GetString("GpaYearlyWeighted", resourceCulture);
            }
        }
        
        internal static string GpaYearlyCompulsory {
            get {
                return ResourceManager.GetString("GpaYearlyCompulsory", resourceCulture);
            }
        }
        
        internal static string GpaSemesterWeighted {
            get {
                return ResourceManager.GetString("GpaSemesterWeighted", resourceCulture);
            }
        }
        
        internal static string GpaSemesterCompulsory {
            get {
                return ResourceManager.GetString("GpaSemesterCompulsory", resourceCulture);
            }
        }
        
        internal static string GpaTotalWeighted {
            get {
                return ResourceManager.GetString("GpaTotalWeighted", resourceCulture);
            }
        }
        
        internal static string GpaTotalCompulsory {
            get {
                return ResourceManager.GetString("GpaTotalCompulsory", resourceCulture);
            }
        }
        
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        internal static string Gdpr_Title {
            get {
                return ResourceManager.GetString("Gdpr_Title", resourceCulture);
            }
        }
        
        internal static string Gdpr_Description {
            get {
                return ResourceManager.GetString("Gdpr_Description", resourceCulture);
            }
        }
        
        internal static string Gdpr_StrictlyNecessary {
            get {
                return ResourceManager.GetString("Gdpr_StrictlyNecessary", resourceCulture);
            }
        }
        
        internal static string Gdpr_NecessaryOnly {
            get {
                return ResourceManager.GetString("Gdpr_NecessaryOnly", resourceCulture);
            }
        }
        
        internal static string Gdpr_AcceptAll {
            get {
                return ResourceManager.GetString("Gdpr_AcceptAll", resourceCulture);
            }
        }
        
        internal static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
    }
}
