//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISOS.Localization {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageHelper {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageHelper() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RISOS.Localization.LanguageHelper", typeof(LanguageHelper).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Abbreviation.
        /// </summary>
        internal static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Academic Details.
        /// </summary>
        internal static string AcademicDetails {
            get {
                return ResourceManager.GetString("AcademicDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add custom subject.
        /// </summary>
        internal static string AddCustomSubject {
            get {
                return ResourceManager.GetString("AddCustomSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add recognized year.
        /// </summary>
        internal static string AddRecognizedYear {
            get {
                return ResourceManager.GetString("AddRecognizedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Adjust study duration.
        /// </summary>
        internal static string AdjustYears {
            get {
                return ResourceManager.GetString("AdjustYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Any.
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Basic Information.
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Classification.
        /// </summary>
        internal static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Completion Type.
        /// </summary>
        internal static string CompletionType {
            get {
                return ResourceManager.GetString("CompletionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Colloquium.
        /// </summary>
        internal static string CompletionTypeCol {
            get {
                return ResourceManager.GetString("CompletionTypeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Course-unit credit.
        /// </summary>
        internal static string CompletionTypeCr {
            get {
                return ResourceManager.GetString("CompletionTypeCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Course-unit credit and examination.
        /// </summary>
        internal static string CompletionTypeCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Course-unit credit and final semester project.
        /// </summary>
        internal static string CompletionTypeCrFsp {
            get {
                return ResourceManager.GetString("CompletionTypeCrFsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Examination.
        /// </summary>
        internal static string CompletionTypeDrEx {
            get {
                return ResourceManager.GetString("CompletionTypeDrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Examination.
        /// </summary>
        internal static string CompletionTypeEx {
            get {
                return ResourceManager.GetString("CompletionTypeEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Except DD.
        /// </summary>
        internal static string CompletionTypeExDd {
            get {
                return ResourceManager.GetString("CompletionTypeExDd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Graded course-unit credit.
        /// </summary>
        internal static string CompletionTypeGCr {
            get {
                return ResourceManager.GetString("CompletionTypeGCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Evaluation of doctoral study.
        /// </summary>
        internal static string CompletionTypeHds {
            get {
                return ResourceManager.GetString("CompletionTypeHds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Evaluation of study.
        /// </summary>
        internal static string CompletionTypeHs {
            get {
                return ResourceManager.GetString("CompletionTypeHs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Final semester project.
        /// </summary>
        internal static string CompletionTypeKp {
            get {
                return ResourceManager.GetString("CompletionTypeKp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No final classification.
        /// </summary>
        internal static string CompletionTypeNone {
            get {
                return ResourceManager.GetString("CompletionTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Recognized colloquium.
        /// </summary>
        internal static string CompletionTypeRCol {
            get {
                return ResourceManager.GetString("CompletionTypeRCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Recognized course-unit credit.
        /// </summary>
        internal static string CompletionTypeRCr {
            get {
                return ResourceManager.GetString("CompletionTypeRCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Recognized course-unit credit and examination.
        /// </summary>
        internal static string CompletionTypeRCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeRCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Recognized.
        /// </summary>
        internal static string CompletionTypeRec {
            get {
                return ResourceManager.GetString("CompletionTypeRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Recognized examination.
        /// </summary>
        internal static string CompletionTypeRecCr {
            get {
                return ResourceManager.GetString("CompletionTypeRecCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Recognized examination.
        /// </summary>
        internal static string CompletionTypeREx {
            get {
                return ResourceManager.GetString("CompletionTypeREx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Recognized graded course-unit credit.
        /// </summary>
        internal static string CompletionTypeRgCr {
            get {
                return ResourceManager.GetString("CompletionTypeRgCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Recognized year of study.
        /// </summary>
        internal static string CompletionTypeRVol {
            get {
                return ResourceManager.GetString("CompletionTypeRVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Col.
        /// </summary>
        internal static string CompletionTypeShortCol {
            get {
                return ResourceManager.GetString("CompletionTypeShortCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cr.
        /// </summary>
        internal static string CompletionTypeShortCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cr,Ex.
        /// </summary>
        internal static string CompletionTypeShortCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cr,Fsp.
        /// </summary>
        internal static string CompletionTypeShortCrFsp {
            get {
                return ResourceManager.GetString("CompletionTypeShortCrFsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dr,Ex.
        /// </summary>
        internal static string CompletionTypeShortDrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortDrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ex.
        /// </summary>
        internal static string CompletionTypeShortEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ex,DD.
        /// </summary>
        internal static string CompletionTypeShortExDd {
            get {
                return ResourceManager.GetString("CompletionTypeShortExDd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný GCr.
        /// </summary>
        internal static string CompletionTypeShortGCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortGCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hds.
        /// </summary>
        internal static string CompletionTypeShortHds {
            get {
                return ResourceManager.GetString("CompletionTypeShortHds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hs.
        /// </summary>
        internal static string CompletionTypeShortHs {
            get {
                return ResourceManager.GetString("CompletionTypeShortHs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Kp.
        /// </summary>
        internal static string CompletionTypeShortKp {
            get {
                return ResourceManager.GetString("CompletionTypeShortKp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný None.
        /// </summary>
        internal static string CompletionTypeShortNone {
            get {
                return ResourceManager.GetString("CompletionTypeShortNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RCol.
        /// </summary>
        internal static string CompletionTypeShortRCol {
            get {
                return ResourceManager.GetString("CompletionTypeShortRCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RCr.
        /// </summary>
        internal static string CompletionTypeShortRCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortRCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RCr,Ex.
        /// </summary>
        internal static string CompletionTypeShortRCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortRCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rec.
        /// </summary>
        internal static string CompletionTypeShortRec {
            get {
                return ResourceManager.GetString("CompletionTypeShortRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RecCr.
        /// </summary>
        internal static string CompletionTypeShortRecCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortRecCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný REx.
        /// </summary>
        internal static string CompletionTypeShortREx {
            get {
                return ResourceManager.GetString("CompletionTypeShortREx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rg,Cr.
        /// </summary>
        internal static string CompletionTypeShortRgCr {
            get {
                return ResourceManager.GetString("CompletionTypeShortRgCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RVol.
        /// </summary>
        internal static string CompletionTypeShortRVol {
            get {
                return ResourceManager.GetString("CompletionTypeShortRVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sp,Cr,Ex.
        /// </summary>
        internal static string CompletionTypeShortSpCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortSpCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sp,Ex.
        /// </summary>
        internal static string CompletionTypeShortSpEx {
            get {
                return ResourceManager.GetString("CompletionTypeShortSpEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SZZ.
        /// </summary>
        internal static string CompletionTypeShortSzz {
            get {
                return ResourceManager.GetString("CompletionTypeShortSzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unknown.
        /// </summary>
        internal static string CompletionTypeShortUnknown {
            get {
                return ResourceManager.GetString("CompletionTypeShortUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Up,Za.
        /// </summary>
        internal static string CompletionTypeShortUpZa {
            get {
                return ResourceManager.GetString("CompletionTypeShortUpZa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Specialization credit and examination.
        /// </summary>
        internal static string CompletionTypeSpCrEx {
            get {
                return ResourceManager.GetString("CompletionTypeSpCrEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Specialization examination.
        /// </summary>
        internal static string CompletionTypeSpEx {
            get {
                return ResourceManager.GetString("CompletionTypeSpEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Final state examination.
        /// </summary>
        internal static string CompletionTypeSzz {
            get {
                return ResourceManager.GetString("CompletionTypeSzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unknown.
        /// </summary>
        internal static string CompletionTypeUnknown {
            get {
                return ResourceManager.GetString("CompletionTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Recognized course-unit credit only.
        /// </summary>
        internal static string CompletionTypeUpZa {
            get {
                return ResourceManager.GetString("CompletionTypeUpZa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Compulsory.
        /// </summary>
        internal static string Compulsory {
            get {
                return ResourceManager.GetString("Compulsory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Compulsory-Elective.
        /// </summary>
        internal static string CompulsoryElective {
            get {
                return ResourceManager.GetString("CompulsoryElective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You have to select subject from every group.
        /// </summary>
        internal static string CompulsoryElectiveErrorMessage {
            get {
                return ResourceManager.GetString("CompulsoryElectiveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Compulsory-Elective.
        /// </summary>
        internal static string CompulsoryElectiveSingle {
            get {
                return ResourceManager.GetString("CompulsoryElectiveSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Compulsory.
        /// </summary>
        internal static string CompulsorySingle {
            get {
                return ResourceManager.GetString("CompulsorySingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný cr.
        /// </summary>
        internal static string Cr {
            get {
                return ResourceManager.GetString("Cr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Credits.
        /// </summary>
        internal static string Credits_y {
            get {
                return ResourceManager.GetString("Credits_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Study duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Elective.
        /// </summary>
        internal static string Elective {
            get {
                return ResourceManager.GetString("Elective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Elective.
        /// </summary>
        internal static string ElectiveSingle {
            get {
                return ResourceManager.GetString("ElectiveSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný e.g. Mathematical Analysis.
        /// </summary>
        internal static string IMA {
            get {
                return ResourceManager.GetString("IMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný e.g. IMA1, IMA2.
        /// </summary>
        internal static string IMAAbbreviation {
            get {
                return ResourceManager.GetString("IMAAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný is required.
        /// </summary>
        internal static string IsRequired_a {
            get {
                return ResourceManager.GetString("IsRequired_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný is required.
        /// </summary>
        internal static string IsRequired_y {
            get {
                return ResourceManager.GetString("IsRequired_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Czech.
        /// </summary>
        internal static string Language_Czech {
            get {
                return ResourceManager.GetString("Language_Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Language change forces refresh of the app after saving.
        /// </summary>
        internal static string LanguageAlert {
            get {
                return ResourceManager.GetString("LanguageAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Change language.
        /// </summary>
        internal static string LanguageToggleTooltip {
            get {
                return ResourceManager.GetString("LanguageToggleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Minimum semester.
        /// </summary>
        internal static string MinimumSemester {
            get {
                return ResourceManager.GetString("MinimumSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Earliest allowed semester.
        /// </summary>
        internal static string MinSemesterHelperText {
            get {
                return ResourceManager.GetString("MinSemesterHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Move to.
        /// </summary>
        internal static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Not applicable.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registered.
        /// </summary>
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Remove recognized year.
        /// </summary>
        internal static string RemoveRecognizedYear {
            get {
                return ResourceManager.GetString("RemoveRecognizedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unable to verify required credits, go to settings to adjust.
        /// </summary>
        internal static string RequiredWarning {
            get {
                return ResourceManager.GetString("RequiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Semester.
        /// </summary>
        internal static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Semester Season.
        /// </summary>
        internal static string SemesterSeason {
            get {
                return ResourceManager.GetString("SemesterSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Academic Settings.
        /// </summary>
        internal static string SettingsDialog_AcademicSettings {
            get {
                return ResourceManager.GetString("SettingsDialog_AcademicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Language.
        /// </summary>
        internal static string SettingsDialog_Language {
            get {
                return ResourceManager.GetString("SettingsDialog_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Override required credits.
        /// </summary>
        internal static string SettingsDialog_OverrideCredits {
            get {
                return ResourceManager.GetString("SettingsDialog_OverrideCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Required Credits.
        /// </summary>
        internal static string SettingsDialog_RequiredCredits {
            get {
                return ResourceManager.GetString("SettingsDialog_RequiredCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        internal static string SettingsDialog_Save {
            get {
                return ResourceManager.GetString("SettingsDialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Settings.
        /// </summary>
        internal static string SettingsDialog_Title {
            get {
                return ResourceManager.GetString("SettingsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show course info.
        /// </summary>
        internal static string ShowCourseInfo {
            get {
                return ResourceManager.GetString("ShowCourseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Study program.
        /// </summary>
        internal static string StudyProgram {
            get {
                return ResourceManager.GetString("StudyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Study progress.
        /// </summary>
        internal static string StudyProgress {
            get {
                return ResourceManager.GetString("StudyProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Subject type.
        /// </summary>
        internal static string SubjectType {
            get {
                return ResourceManager.GetString("SubjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Summer.
        /// </summary>
        internal static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unassigned.
        /// </summary>
        internal static string Unassigned {
            get {
                return ResourceManager.GetString("Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unassigned Subjects.
        /// </summary>
        internal static string UnassignedSubjects {
            get {
                return ResourceManager.GetString("UnassignedSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Winter.
        /// </summary>
        internal static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Years.
        /// </summary>
        internal static string Years_Few {
            get {
                return ResourceManager.GetString("Years_Few", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Years.
        /// </summary>
        internal static string Years_Many {
            get {
                return ResourceManager.GetString("Years_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Year.
        /// </summary>
        internal static string Years_One {
            get {
                return ResourceManager.GetString("Years_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Year total.
        /// </summary>
        internal static string YearTotal {
            get {
                return ResourceManager.GetString("YearTotal", resourceCulture);
            }
        }
    }
}
